package views;

import backupmanagment.BackupManager;

import javax.swing.*;
import java.awt.*;
import java.util.Date;

/**
 * This class wraps all components of the aplication main window.
 *
 * <br/>
 * Created by Martin Sicho on 26.5.2014.
 */
public class MainWindow extends JFrame implements BackupViewer {
    // containers
    private JPanel pContainer;
    private JPanel pIntro;
    private JScrollPane scrlPane;
    private JPanel pButtons;

    // components
    private JTable table;
    private JButton btSyncSele;
    private JButton btSyncAll;
    private JButton btCreateNew;
    private JLabel lbIntro;

    // members
    String mBackupName;

    public MainWindow() {
        setTitle("Simple Backup System in Java");
        getContentPane().add($$$getRootComponent$$$());
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        updateTable();
        pack();
        setResizable(false);
        setLocationByPlatform(true);
    }

    public void showGUI() {
        setVisible(true);
    }

    @Override
    public void showBackupInfo(String name, String original, String backup, boolean shallow, Date date) {
        // TODO: implement the logic of table update
    }

    @Override
    public String getBackupName() {
        return mBackupName;
    }

    @Override
    public void setBackupName(String name) {
        mBackupName = name;
    }

    // private methods

    private void updateTable() {
        new BackupManager().updateView(this);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pContainer = new JPanel();
        pContainer.setLayout(new BorderLayout(0, 0));
        pButtons = new JPanel();
        pButtons.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        pButtons.setAlignmentX(0.5f);
        pContainer.add(pButtons, BorderLayout.SOUTH);
        btSyncSele = new JButton();
        btSyncSele.setActionCommand("btSyncSele");
        btSyncSele.setText("Synchronize Seleceted");
        btSyncSele.setToolTipText("Synchronize selected backups.");
        pButtons.add(btSyncSele);
        btSyncAll = new JButton();
        btSyncAll.setActionCommand("btSyncAll");
        btSyncAll.setText("Synchronize All");
        btSyncAll.setToolTipText("Synchronize all backups.");
        pButtons.add(btSyncAll);
        btCreateNew = new JButton();
        btCreateNew.setActionCommand("btCreateNew");
        btCreateNew.setText("Create New Backup");
        btCreateNew.setToolTipText("Create new backup.");
        pButtons.add(btCreateNew);
        scrlPane = new JScrollPane();
        scrlPane.setPreferredSize(new Dimension(453, 200));
        pContainer.add(scrlPane, BorderLayout.CENTER);
        table = new JTable();
        scrlPane.setViewportView(table);
        pIntro = new JPanel();
        pIntro.setLayout(new BorderLayout(0, 0));
        pContainer.add(pIntro, BorderLayout.NORTH);
        pIntro.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 3, 5, 3), null));
        lbIntro = new JLabel();
        lbIntro.setText("Introductory text.");
        pIntro.add(lbIntro, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pContainer;
    }
}
