package views;

import backupmanagment.BackupManager;
import views.tablerenderers.*;

import javax.swing.*;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.util.Set;

/**
 * This class wraps all components of the aplication main window.
 * <p/>
 * <br/>
 * Created by Martin Sicho on 26.5.2014.
 */
public class MainWindow extends JFrame {
    // containers
    private JPanel pContainer;
    private JPanel pIntro;
    private JScrollPane scrlPane;
    private JPanel pButtons;

    // components
    private JTable tbTable;
    private JButton btSyncSele;
    private JButton btSyncAll;
    private JButton btCreateNew;
    private JLabel lbIntro;
    private JButton btDelSelected;

    // members
    BackupTableModel mTableModel;
    BackupManager mBackupManager;

    public MainWindow() {
        mBackupManager = new BackupManager();
        setTitle("Simple Backup System in Java");
        getContentPane().add($$$getRootComponent$$$());
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        setUpTable();

        attachButtonListeners();

        setMinimumSize(new Dimension(600, 200));
        pack();
        setLocationByPlatform(true);
    }

    public void showGUI() {
        setVisible(true);
    }

    public void updateTable() {
        mTableModel.update();
        tbTable.repaint();
    }

    // private methods

    private void setUpTable() {
        tbTable.setRowHeight(25);
        mTableModel = new BackupTableModel(mBackupManager);
        tbTable.setModel(mTableModel);
        tbTable.setDefaultRenderer(Date.class, new BackupTableDateRenderer());
        TableColumn col = tbTable.getColumn("Synchronize");
        col.setCellEditor(new BackupTableButtonEditor());
        col.setCellRenderer(new BackupTableSyncButtonRenderer());
        col.setWidth(100);
        col = tbTable.getColumn("Selected");
        //col.setCellRenderer(new BackupTableSelectedRenderer());
        col.setMaxWidth(60);
        col = tbTable.getColumn("Shallow");
        col.setMaxWidth(60);
        col = tbTable.getColumn("Name");
        col.setPreferredWidth(50);
    }

    private void attachButtonListeners() {
        btSyncSele.addMouseListener(new MouseAdapter() {
            /**
             * {@inheritDoc}
             *
             * @param e
             */
            @Override
            public void mouseClicked(MouseEvent e) {
                Set<String> backup_names = mTableModel.getSelectedBackups();
                for (String name : backup_names) {
                    mBackupManager.synchronize(name);
                }
                updateTable();
            }
        });

        btSyncAll.addMouseListener(new MouseAdapter() {
            /**
             * {@inheritDoc}
             *
             * @param e
             */
            @Override
            public void mouseClicked(MouseEvent e) {
                mBackupManager.synchronize();
                updateTable();
            }
        });

        btCreateNew.addMouseListener(new MouseAdapter() {
            /**
             * {@inheritDoc}
             *
             * @param e
             */
            @Override
            public void mouseClicked(MouseEvent e) {
                new Thread(new CreateNewBackupDialog(mBackupManager, MainWindow.this)).start();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pContainer = new JPanel();
        pContainer.setLayout(new BorderLayout(0, 0));
        pButtons = new JPanel();
        pButtons.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        pButtons.setAlignmentX(0.5f);
        pContainer.add(pButtons, BorderLayout.SOUTH);
        btDelSelected = new JButton();
        btDelSelected.setActionCommand("btDelSelected");
        btDelSelected.setText("Delete Selected");
        btDelSelected.setToolTipText("Delete selected backups. Only removes backups from the application. All files are preserved.");
        pButtons.add(btDelSelected);
        btSyncSele = new JButton();
        btSyncSele.setActionCommand("btSyncSele");
        btSyncSele.setText("Synchronize Seleceted");
        btSyncSele.setToolTipText("Synchronize selected backups.");
        pButtons.add(btSyncSele);
        btSyncAll = new JButton();
        btSyncAll.setActionCommand("btSyncAll");
        btSyncAll.setText("Synchronize All");
        btSyncAll.setToolTipText("Synchronize all backups.");
        pButtons.add(btSyncAll);
        btCreateNew = new JButton();
        btCreateNew.setActionCommand("btCreateNew");
        btCreateNew.setText("Create New Backup");
        btCreateNew.setToolTipText("Create new backup.");
        pButtons.add(btCreateNew);
        scrlPane = new JScrollPane();
        scrlPane.setPreferredSize(new Dimension(700, 200));
        pContainer.add(scrlPane, BorderLayout.CENTER);
        tbTable = new JTable();
        scrlPane.setViewportView(tbTable);
        pIntro = new JPanel();
        pIntro.setLayout(new BorderLayout(0, 0));
        pContainer.add(pIntro, BorderLayout.NORTH);
        pIntro.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 3, 5, 3), null));
        lbIntro = new JLabel();
        lbIntro.setText("Introductory text.");
        pIntro.add(lbIntro, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pContainer;
    }
}
