package views;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Krwemil on 26.5.2014.
 */
public class MainWindow extends JFrame {
    private JPanel container;
    private JTable table;
    private JButton btSyncSele;
    private JButton btSyncAll;
    private JButton btCreateNew;
    private JLabel intro;
    private JPanel pButtons;
    private JScrollPane scrlPane;
    private JPanel pIntro;

    public void showGUI() {
        this.getContentPane().add(this.$$$getRootComponent$$$());
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.pack();
        this.setResizable(false);
        this.setLocationByPlatform(true);
        this.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        container = new JPanel();
        container.setLayout(new BorderLayout(0, 0));
        pButtons = new JPanel();
        pButtons.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        pButtons.setAlignmentX(0.5f);
        container.add(pButtons, BorderLayout.SOUTH);
        btSyncSele = new JButton();
        btSyncSele.setActionCommand("btSyncSele");
        btSyncSele.setText("Synchronize Seleceted");
        btSyncSele.setToolTipText("Synchronize selected backups.");
        pButtons.add(btSyncSele);
        btSyncAll = new JButton();
        btSyncAll.setActionCommand("btSyncAll");
        btSyncAll.setText("Synchronize All");
        btSyncAll.setToolTipText("Synchronize all backups.");
        pButtons.add(btSyncAll);
        btCreateNew = new JButton();
        btCreateNew.setActionCommand("btCreateNew");
        btCreateNew.setText("Create New Backup");
        btCreateNew.setToolTipText("Create new backup.");
        pButtons.add(btCreateNew);
        scrlPane = new JScrollPane();
        scrlPane.setPreferredSize(new Dimension(453, 200));
        container.add(scrlPane, BorderLayout.CENTER);
        table = new JTable();
        scrlPane.setViewportView(table);
        pIntro = new JPanel();
        pIntro.setLayout(new BorderLayout(0, 0));
        container.add(pIntro, BorderLayout.NORTH);
        pIntro.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 3, 5, 3), null));
        intro = new JLabel();
        intro.setText("Introductory text.");
        pIntro.add(intro, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return container;
    }
}
